services:
  mariadb:
    image: mariadb:10.10
    hostname: mariadb
    container_name: mariadb
    network_mode: host
    ports:
      - 13306:3306
    volumes:
      - ./data/slurm-maria-db:/var/lib/mysql
    environment:
      - MARIADB_USER=slurm
      - MARIADB_PASSWORD=slurm
      - MARIADB_ROOT_PASSWORD=dbroot-password
      - MARIADB_DATABASE=slurm
  slurmdbd:
    image: slurm-dbd:latest
    hostname: slurmdbd
    user: slurm
    network_mode: host
    volumes:
      - ./workspace:/home/slurm
      - ./etc/munge/munge.key:/etc/munge/munge.key
      - ./etc/slurm-llnl/cgroup.conf:/etc/slurm-llnl/cgroup.conf            
      - ./etc/slurm-llnl/gres.conf:/etc/slurm-llnl/gres.conf            
      - ./etc/slurm-llnl/slurm.conf:/etc/slurm-llnl/slurm.conf            
      - ./etc/slurm-llnl/slurmdbd.conf:/etc/slurm-llnl/slurmdbd.conf                 
      - ./dbd/docker-entrypoint.sh:/etc/slurm-llnl/docker-entrypoint.sh                  
#    ports:
#      - 17031:7031
#    depends:
#      - mariadb
  slurmmaster:
    image: slurm-master:latest
    hostname: slurmmaster
    user: admin
    network_mode: host
    volumes:
      - ./workspace:/home/admin
      - ./etc/munge/munge.key:/etc/munge/munge.key      
      - ./etc/slurm-llnl/cgroup.conf:/etc/slurm-llnl/cgroup.conf            
      - ./etc/slurm-llnl/gres.conf:/etc/slurm-llnl/gres.conf            
      - ./etc/slurm-llnl/slurm.conf:/etc/slurm-llnl/slurm.conf            
      - ./etc/slurm-llnl/slurmdbd.conf:/etc/slurm-llnl/slurmdbd.conf                 
      - ./master/docker-entrypoint.sh:/etc/slurm-llnl/docker-entrypoint.sh                  
#    ports:
#      - 16817:6817
#      - 16819:6819      
#    depends:
#      - slurmdbd
  slurmnode1:
    image: slurm-node:latest
    hostname: slurmnode1
    user: admin
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]    
    volumes:
      - ./workspace:/home/admin
      - ./etc/munge/munge.key:/etc/munge/munge.key      
      - ./etc/slurm-llnl/cgroup.conf:/etc/slurm-llnl/cgroup.conf            
      - ./etc/slurm-llnl/gres.conf:/etc/slurm-llnl/gres.conf            
      - ./etc/slurm-llnl/slurm.conf:/etc/slurm-llnl/slurm.conf            
      - ./etc/slurm-llnl/slurmdbd.conf:/etc/slurm-llnl/slurmdbd.conf                 
      - ./node/docker-entrypoint.sh:/etc/slurm-llnl/docker-entrypoint.sh                                
 #   ports:
 #     - 16818:6818
 #   depends:
 #     - slurmmaster
  slurmjupyter:
    image: slurm-jupyter:latest
    hostname: slurmjupyter
    user: admin
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]        
    volumes:
      - ./workspace:/home/admin 
      - ./etc/munge/munge.key:/etc/munge/munge.key      
      - ./etc/slurm-llnl/cgroup.conf:/etc/slurm-llnl/cgroup.conf            
      - ./etc/slurm-llnl/gres.conf:/etc/slurm-llnl/gres.conf            
      - ./etc/slurm-llnl/slurm.conf:/etc/slurm-llnl/slurm.conf            
      - ./etc/slurm-llnl/slurmdbd.conf:/etc/slurm-llnl/slurmdbd.conf                 
      - ./jupyter/docker-entrypoint.sh:/etc/slurm-llnl/docker-entrypoint.sh                                
#    ports: 
#      - 18888:8888
#    depends:
#      - slurmmaster
volumes:
  shared.vol:

networks:
  host:
    name: host
    external: true
