services:
  mariadb:
    image: mariadb:10.10
    hostname: mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./data/slurm-mariadb:/var/lib/mysql
    environment:
      - MARIADB_USER=slurm
      - MARIADB_PASSWORD=slurm
      - MARIADB_ROOT_PASSWORD=dbroot-password
      - MARIADB_DATABASE=slurm
  slurmdbd:
    image: slurm-dbd:latest
    hostname: slurmdbd
    user: slurm
    volumes:
      - /mnt/workspace:/home/slurm
    ports:
      - 7031:7031
    links:
      - mariadb
  slurmmaster:
    image: slurm-master:latest
    hostname: slurmmaster
    user: admin
    volumes:
      - /mnt/workspace:/home/admin
    ports:
      - 6817:6817
      - 6819:6819
    links:
      - slurmdbd
  slurmnode1:
    image: slurm-node:latest
    hostname: slurmnode1
    user: admin
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - /mnt/workspace:/home/admin
    ports:
      - 6818:6818
    links:
      - slurmmaster
  slurmnode2:
    image: slurm-node:latest
    hostname: slurmnode2
    user: admin
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [ gpu ]
    volumes:
      - /mnt/workspace:/home/admin
    links:
      - slurmmaster
  slurmnode3:
    image: slurm-node:latest
    hostname: slurmnode3
    user: admin
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [ gpu ]
    volumes:
      - /mnt/workspace:/home/admin
    links:
      - slurmmaster      
  slurmjupyter:
    image: slurm-jupyter:latest
    hostname: slurmjupyter
    user: admin
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - /mnt/workspace:/home/admin
    ports:
      - 8888:8888
    links:
      - slurmmaster
volumes:
  slurm-workspace:
  slurm-mariadb:
